#!/bin/bash
set -e

if [ "$1" = "build" ] || [ "$2" = "build" ]
  then
    ./build
fi

if [ "$1" = "forever" ] || [ "$2" = "forever" ]
  then
    node forever.js
  else
  	node --harmony ./src/server.js
fi


